INSERT INTO ADDRESS (STREET, NUMBER_HOME, POST_CODE, CITY, COUNTRY)
            VALUES ('Arkuszowa', '45', '00-001', 'Warszawa', 'Polska');
INSERT INTO ADDRESS (STREET, NUMBER_HOME, POST_CODE, CITY, COUNTRY)
            VALUES ('Kosmiczna', '1', '05-303', 'Mińsk Mazowiecki', 'Polska');
INSERT INTO ADDRESS (STREET, NUMBER_HOME, POST_CODE, CITY, COUNTRY)
            VALUES ('Cmentarna', '12', '05-660', 'Warka', 'Polska');
INSERT INTO ADDRESS (STREET, NUMBER_HOME, POST_CODE, CITY, COUNTRY)
            VALUES ('Ignacego Skorupki', '1', '90-001', 'Łódź', 'Polska');
INSERT INTO ADDRESS (STREET, NUMBER_HOME, POST_CODE, CITY, COUNTRY)
            VALUES ('Aleja Stanisława Jachowicza', '4A', '09-100', 'Płock', 'Polska');

INSERT INTO CAR_DEALER (NAME_OF_FIRM, ADDRESS_ID, PHONE_NUMBER, OPEN_FROM, OPEN_TO, CAR_DEALER_IMAGE)
            VALUES ('Auto Plaza', 1, '852-741-963', '10', '18', '/img/carDealers/1/cardealer-main.jpg');
INSERT INTO CAR_DEALER (NAME_OF_FIRM, ADDRESS_ID, PHONE_NUMBER, OPEN_FROM, OPEN_TO, CAR_DEALER_IMAGE)
            VALUES ('Aries Motor', 2, '123-456-789', '9', '17', '/img/carDealers/2/cardealer-main.jpg');
INSERT INTO CAR_DEALER (NAME_OF_FIRM, ADDRESS_ID, PHONE_NUMBER, OPEN_FROM, OPEN_TO, CAR_DEALER_IMAGE)
            VALUES ('Odyssey Dealer', 3, NULL, '12', '20', '/img/carDealers/3/cardealer-main.jpg');
INSERT INTO CAR_DEALER (NAME_OF_FIRM, ADDRESS_ID, PHONE_NUMBER, OPEN_FROM, OPEN_TO, CAR_DEALER_IMAGE)
            VALUES ('AutoAdamski', 4, '456-123-789', '8', '20', '/img/carDealers/4/cardealer-main.jpg');
INSERT INTO CAR_DEALER (NAME_OF_FIRM, ADDRESS_ID, PHONE_NUMBER, OPEN_FROM, OPEN_TO, CAR_DEALER_IMAGE)
            VALUES ('AutoSalon24', 5, NULL,  '12', '22', '/img/carDealers/5/cardealer-main.jpg');

INSERT INTO CAR (CAR_DEALER_ID, MAKE, MODEL, YEAR_OF_PRODUCTION, USED, PRICE, FUEL, ENGINE, AIR_CONDITIONING, DATE_POSTED, DATE_SOLD, CAR_IMAGE)
            VALUES (1, 'Opel', 'Astra', 2002, 100000, 45900, 'GAS', 1.6, FALSE, '2018-08-30', NULL, '/img/cars/1/car-main.jpg');
INSERT INTO CAR (CAR_DEALER_ID, MAKE, MODEL, YEAR_OF_PRODUCTION, USED, PRICE, FUEL, ENGINE, AIR_CONDITIONING, DATE_POSTED, DATE_SOLD)
            VALUES (1, 'Renault', 'Clio', 2006, 67000, 37900, 'PETROL', 1.6, TRUE, '2018-08-24', NULL);
INSERT INTO CAR (CAR_DEALER_ID, MAKE, MODEL, YEAR_OF_PRODUCTION, USED, PRICE, FUEL, ENGINE, AIR_CONDITIONING, DATE_POSTED, DATE_SOLD, CAR_IMAGE)
            VALUES (1, 'Audi', 'A4', 2010, 54000, 70000, 'PETROL', 2.0, TRUE, '2018-09-02', NULL, '/img/cars/3/car-main.jpg');
INSERT INTO CAR (CAR_DEALER_ID, MAKE, MODEL, YEAR_OF_PRODUCTION, USED, PRICE, FUEL, ENGINE, AIR_CONDITIONING, DATE_POSTED, DATE_SOLD)
            VALUES (1, 'Renault', 'Scenic', 2000, 159000, 6500, 'PETROL', 1.2, FALSE, '2018-09-01', NULL);
INSERT INTO CAR (CAR_DEALER_ID, MAKE, MODEL, YEAR_OF_PRODUCTION, USED, PRICE, FUEL, ENGINE, AIR_CONDITIONING, DATE_POSTED, DATE_SOLD, CAR_IMAGE)
            VALUES (1, 'Peugeot', '207', 2010, 75000, 15700, 'GAS', 1.4, TRUE, '2018-08-27', NULL, '/img/cars/5/car-main.jpg');

INSERT INTO CAR (CAR_DEALER_ID, MAKE, MODEL, YEAR_OF_PRODUCTION, USED, PRICE, FUEL, ENGINE, AIR_CONDITIONING, DATE_POSTED, DATE_SOLD)
            VALUES (2, 'Citroen', 'C5', 1995, 250000, 37980, 'OIL', 1.8, TRUE, '2018-08-24', NULL);
INSERT INTO CAR (CAR_DEALER_ID, MAKE, MODEL, YEAR_OF_PRODUCTION, USED, PRICE, FUEL, ENGINE, AIR_CONDITIONING, DATE_POSTED, DATE_SOLD, CAR_IMAGE)
            VALUES (2, 'Suzuki', 'Swift', 2012, 85000, 14450, 'PETROL', 1.3, FALSE, '2018-08-29', NULL, '/img/cars/7/car-main.jpg');
INSERT INTO CAR (CAR_DEALER_ID, MAKE, MODEL, YEAR_OF_PRODUCTION, USED, PRICE, FUEL, ENGINE, AIR_CONDITIONING, DATE_POSTED, DATE_SOLD, CAR_IMAGE)
            VALUES (2, 'Peugeot', '207', 2011, 85000, 14700, 'PETROL', 1.2, TRUE, '2018-08-31', NULL, '/img/cars/8/car-main.jpg');
INSERT INTO CAR (CAR_DEALER_ID, MAKE, MODEL, YEAR_OF_PRODUCTION, USED, PRICE, FUEL, ENGINE, AIR_CONDITIONING, DATE_POSTED, DATE_SOLD)
            VALUES (2, 'Renault', 'Clio', 2010, 88000, 20900, 'OIL', 1.8, TRUE, '2018-09-01', NULL);

INSERT INTO CAR (CAR_DEALER_ID, MAKE, MODEL, YEAR_OF_PRODUCTION, USED, PRICE, FUEL, ENGINE, AIR_CONDITIONING, DATE_POSTED, DATE_SOLD)
            VALUES (3, 'Renault', 'Clio', 2002, 152000, 3450, 'PETROL', 1.2, FALSE, '2018-08-28', NULL);
INSERT INTO CAR (CAR_DEALER_ID, MAKE, MODEL, YEAR_OF_PRODUCTION, USED, PRICE, FUEL, ENGINE, AIR_CONDITIONING, DATE_POSTED, DATE_SOLD, CAR_IMAGE)
            VALUES (3, 'Mazda', 'CX-5', 2015, 125000, 85900, 'OIL', 2.5, TRUE, '2018-08-23', NULL, '/img/cars/11/car-main.jpg');
INSERT INTO CAR (CAR_DEALER_ID, MAKE, MODEL, YEAR_OF_PRODUCTION, USED, PRICE, FUEL, ENGINE, AIR_CONDITIONING, DATE_POSTED, DATE_SOLD, CAR_IMAGE)
            VALUES (3, 'Ford', 'Focus', 1999, 116000, 25900, 'GAS', 1.6, TRUE, '2018-08-26', NULL, '/img/cars/12/car-main.jpg');
INSERT INTO CAR (CAR_DEALER_ID, MAKE, MODEL, YEAR_OF_PRODUCTION, USED, PRICE, FUEL, ENGINE, AIR_CONDITIONING, DATE_POSTED, DATE_SOLD)
            VALUES (3, 'Renault', 'Clio', 2006, 251000, 6350, 'GAS', 1.2, FALSE, '2018-08-27', NULL);
INSERT INTO CAR (CAR_DEALER_ID, MAKE, MODEL, YEAR_OF_PRODUCTION, USED, PRICE, FUEL, ENGINE, AIR_CONDITIONING, DATE_POSTED, DATE_SOLD, CAR_IMAGE)
            VALUES (3, 'Skoda', 'Fabia', 2006, 2013, 23900, 'OIL', 1.6, TRUE, '2018-09-02', NULL, '/img/cars/14/car-main.jpg');
INSERT INTO CAR (CAR_DEALER_ID, MAKE, MODEL, YEAR_OF_PRODUCTION, USED, PRICE, FUEL, ENGINE, AIR_CONDITIONING, DATE_POSTED, DATE_SOLD)
            VALUES (3, 'Suzuki', 'Swift', 2012, 25300, 55000, 'PETROL', 1.2, TRUE, '2018-09-02', NULL);
INSERT INTO CAR (CAR_DEALER_ID, MAKE, MODEL, YEAR_OF_PRODUCTION, USED, PRICE, FUEL, ENGINE, AIR_CONDITIONING, DATE_POSTED, DATE_SOLD, CAR_IMAGE)
            VALUES (3, 'Audi', 'A4', 2018, 12000, 125000, 'PETROL', 2.2, TRUE, '2018-09-01', NULL, '/img/cars/16/car-main.jpg');

INSERT INTO CAR (CAR_DEALER_ID, MAKE, MODEL, YEAR_OF_PRODUCTION, USED, PRICE, FUEL, ENGINE, AIR_CONDITIONING, DATE_POSTED, DATE_SOLD)
            VALUES (4, 'Corvette', 'C6', 2006, 125000, 103000, 'PETROL', 3.0, FALSE, '2018-08-24', NULL);
INSERT INTO CAR (CAR_DEALER_ID, MAKE, MODEL, YEAR_OF_PRODUCTION, USED, PRICE, FUEL, ENGINE, AIR_CONDITIONING, DATE_POSTED, DATE_SOLD, CAR_IMAGE)
            VALUES (4, 'Toyota', 'Yaris', 2016, 100000, 37900, 'GAS', 1.3, TRUE, '2018-08-26', NULL, '/img/cars/18/car-main.jpg');
INSERT INTO CAR (CAR_DEALER_ID, MAKE, MODEL, YEAR_OF_PRODUCTION, USED, PRICE, FUEL, ENGINE, AIR_CONDITIONING, DATE_POSTED, DATE_SOLD)
            VALUES (4, 'Nissan', 'Almera', 2001, 254000, 5000, 'PETROL', 1.6, TRUE, '2018-08-25', NULL);
INSERT INTO CAR (CAR_DEALER_ID, MAKE, MODEL, YEAR_OF_PRODUCTION, USED, PRICE, FUEL, ENGINE, AIR_CONDITIONING, DATE_POSTED, DATE_SOLD, CAR_IMAGE)
            VALUES (4, 'Renault', 'Clio', 2014, 45000, 54000, 'PETROL', 1.8, TRUE, '2018-08-29', NULL, '/img/cars/20/car-main.jpg');
INSERT INTO CAR (CAR_DEALER_ID, MAKE, MODEL, YEAR_OF_PRODUCTION, USED, PRICE, FUEL, ENGINE, AIR_CONDITIONING, DATE_POSTED, DATE_SOLD, CAR_IMAGE)
            VALUES (4, 'Peugeot', '207', 2010, 155000, 25000, 'GAS', 1.4, FALSE, '2018-08-31', NULL, '/img/cars/21/car-main.jpg');
INSERT INTO CAR (CAR_DEALER_ID, MAKE, MODEL, YEAR_OF_PRODUCTION, USED, PRICE, FUEL, ENGINE, AIR_CONDITIONING, DATE_POSTED, DATE_SOLD, CAR_IMAGE)
            VALUES (4, 'Peugeot', '207', 2012, 120000, 37500, 'PETROL', 1.4, TRUE, '2018-09-02', NULL, '/img/cars/22/car-main.jpg');

INSERT INTO CAR (CAR_DEALER_ID, MAKE, MODEL, YEAR_OF_PRODUCTION, USED, PRICE, FUEL, ENGINE, AIR_CONDITIONING, DATE_POSTED, DATE_SOLD, CAR_IMAGE)
            VALUES (5, 'Citroen', 'C5', 2015, 127000, 85000, 'GAS', 1.4, FALSE, '2018-08-29', NULL, '/img/cars/23/car-main.jpg');
INSERT INTO CAR (CAR_DEALER_ID, MAKE, MODEL, YEAR_OF_PRODUCTION, USED, PRICE, FUEL, ENGINE, AIR_CONDITIONING, DATE_POSTED, DATE_SOLD)
            VALUES (5, 'Suzuki', 'Swift', 2010, 45000, 27800, 'PETROL', 1.2, TRUE, '2018-08-28', NULL);
INSERT INTO CAR (CAR_DEALER_ID, MAKE, MODEL, YEAR_OF_PRODUCTION, USED, PRICE, FUEL, ENGINE, AIR_CONDITIONING, DATE_POSTED, DATE_SOLD)
            VALUES (5, 'Opel', 'Astra', 1992, 352000, 1200, 'GAS', 1.4, FALSE, '2018-09-02', NULL);
INSERT INTO CAR (CAR_DEALER_ID, MAKE, MODEL, YEAR_OF_PRODUCTION, USED, PRICE, FUEL, ENGINE, AIR_CONDITIONING, DATE_POSTED, DATE_SOLD, CAR_IMAGE)
            VALUES (5, 'Renault', 'Clio', 2016, 185000, 25400, 'OIL', 1.4, TRUE, '2018-09-02', NULL, '/img/cars/26/car-main.jpg');
INSERT INTO CAR (CAR_DEALER_ID, MAKE, MODEL, YEAR_OF_PRODUCTION, USED, PRICE, FUEL, ENGINE, AIR_CONDITIONING, DATE_POSTED, DATE_SOLD)
            VALUES (5, 'Audi', 'A4', 2002, 195000, 12400, 'PETROL', 2.0, FALSE, '2018-09-01', NULL);
INSERT INTO CAR (CAR_DEALER_ID, MAKE, MODEL, YEAR_OF_PRODUCTION, USED, PRICE, FUEL, ENGINE, AIR_CONDITIONING, DATE_POSTED, DATE_SOLD, CAR_IMAGE)
            VALUES (5, 'Suzuki', 'Swift', 2016, 37000, 45500, 'PETROL', 1.3, TRUE, '2018-08-29', NULL, '/img/cars/28/car-main.jpg');
INSERT INTO CAR (CAR_DEALER_ID, MAKE, MODEL, YEAR_OF_PRODUCTION, USED, PRICE, FUEL, ENGINE, AIR_CONDITIONING, DATE_POSTED, DATE_SOLD)
            VALUES (5, 'Audi', 'A4', 2014, 68000, 68000, 'OIL', 2.0, TRUE, '2018-08-31', NULL);
