CREATE TABLE CAR(
  CAR_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  CAR_DEALER_ID BIGINT NOT NULL,
  MAKE VARCHAR(20) NOT NULL,
  MODEL VARCHAR(20) NOT NULL,
  YEAR_OF_PRODUCTION YEAR NOT NULL,
  USED BIGINT NOT NULL,
  PRICE BIGINT NOT NULL,
  FUEL ENUM ('GAS', 'PETROL', 'OIL') NOT NULL,
  ENGINE FLOAT NOT NULL,
  AIR_CONDITIONING BOOLEAN NOT NULL,
  DATE_POSTED DATE NOT NULL,
  DATE_SOLD DATE,
  CAR_IMAGE VARCHAR(100)
);

CREATE TABLE CAR_DEALER(
  CAR_DEALER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME_OF_FIRM VARCHAR(50) UNIQUE NOT NULL,
  ADDRESS_ID BIGINT UNIQUE NOT NULL,
  PHONE_NUMBER VARCHAR(11),
  OPEN_FROM VARCHAR(2) NOT NULL,
  OPEN_TO VARCHAR(2) NOT NULL,
  CAR_DEALER_IMAGE VARCHAR(100)
);

CREATE TABLE ADDRESS(
  ADDRESS_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  STREET VARCHAR(50) NOT NULL,
  NUMBER_HOME VARCHAR(4) NOT NULL,
  POST_CODE VARCHAR(6) NOT NULL,
  CITY VARCHAR(50) NOT NULL,
  COUNTRY VARCHAR(30) NOT NULL
);

ALTER TABLE CAR_DEALER ADD FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID);
ALTER TABLE CAR ADD FOREIGN KEY (CAR_DEALER_ID) REFERENCES CAR_DEALER(CAR_DEALER_ID);
CREATE INDEX IDX_POST_DATE ON CAR(DATE_POSTED);
